name: Doc

on:
  push:
    branches:
      - main
  workflow_dispatch:


permissions:
  contents: write
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Tester
        uses: actions/checkout@v3
        with:
          repository: rinuxos/rinux-workflow-tester
          path: '.'
      - name: Checkout rinuxcore
        uses: actions/checkout@v3
        with:
          path: 'rinuxcore'
      - name: Checkout std3
        uses: actions/checkout@v3
        with:
          repository: rinuxos/std3
          path: 'std3'
      - name: Checkout config
        uses: actions/checkout@v3
        with:
          repository: rinuxos/rinuxconfig
          path: 'config'
      - name: Checkout Bootloader
        uses: actions/checkout@v3
        with:
          repository: rinuxos/bootloader
          path: 'bootloader'
      - run: rustup target add x86_64-unknown-linux-gnu
      - run: rustup toolchain add nightly
      - run: rustup default nightly
      - run: rustup component add rust-src --toolchain nightly-x86_64-unknown-linux-gnu
      - run: cargo +nightly doc -p "rinuxcore"
      - uses: "finnp/create-file-action@master"
        env:
          FILE_NAME: "./target/doc/index.html"
          FILE_DATA: '<!DOCTYPE html><html><head><meta http-equiv="refresh"content="0;url='./rinuxcore'"/></head></html>' #Redirect to default page
    
      - name: Setup Pages
        uses: actions/configure-pages@v2
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v1
        with:
          path: './target/doc/'
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v1