name: Rust

on: [push, pull_request, workflow_dispatch, release]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout rinuxcore
      uses: actions/checkout@v3
      with:
        path: 'rinuxcore'
    - name: Checkout std3
      uses: actions/checkout@v3
      with:
        repository: AtomicGamer9523/std3
        path: 'std3'
    - name: Checkout config
      uses: actions/checkout@v3
      with:
        repository: AtomicGamer9523/rinuxconfig
        path: 'config'
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose

  clippy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout rinuxcore
        uses: actions/checkout@v3
        with:
          path: 'rinuxcore'
      - name: Checkout std3
        uses: actions/checkout@v3
        with:
          repository: AtomicGamer9523/std3
          path: 'std3'
      - name: Checkout config
        uses: actions/checkout@v3
        with:
          repository: AtomicGamer9523/rinuxconfig
          path: 'config'
      - run: rustup component add clippy
      - run: rustup target add nightly-x86_64-unknown-linux-gnu
      - uses: actions-rs/clippy-check@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          toolchain: nightly
          args: --all-features
