name: Build And Test

on: [push, pull_request, workflow_dispatch, release]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Tester
      uses: actions/checkout@v3
      with:
        repository: rinuxos/rinux-workflow-tester
        path: '.'
    - name: Checkout rinuxcore
      uses: actions/checkout@v3
      with:
        path: 'rinuxcore'
    - name: Checkout std3
      uses: actions/checkout@v3
      with:
        repository: rinuxos/std3
        path: 'std3'
    - name: Checkout config
      uses: actions/checkout@v3
      with:
        repository: rinuxos/rinuxconfig
        path: 'config'
    - name: Checkout Bootloader
      uses: actions/checkout@v3
      with:
        repository: rinuxos/bootloader
        path: 'bootloader'
    - run: rustup target add x86_64-unknown-linux-gnu
    - run: rustup toolchain add nightly
    - run: rustup default nightly
    - run: rustup component add rust-src --toolchain nightly-x86_64-unknown-linux-gnu
    - name: Build
      run: cargo +nightly build --verbose

  clippy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Tester
        uses: actions/checkout@v3
        with:
          repository: rinuxos/rinux-workflow-tester
          path: '.'
      - name: Checkout rinuxcore
        uses: actions/checkout@v3
        with:
          path: 'rinuxcore'
      - name: Checkout std3
        uses: actions/checkout@v3
        with:
          repository: rinuxos/std3
          path: 'std3'
      - name: Checkout config
        uses: actions/checkout@v3
        with:
          repository: rinuxos/rinuxconfig
          path: 'config'
      - name: Checkout Bootloader
        uses: actions/checkout@v3
        with:
          repository: rinuxos/bootloader
          path: 'bootloader'
      - run: rustup target add x86_64-unknown-linux-gnu
      - run: rustup toolchain add nightly
      - run: rustup component add clippy --toolchain nightly-x86_64-unknown-linux-gnu
      - run: rustup component add rust-src --toolchain nightly-x86_64-unknown-linux-gnu
      - uses: actions-rs/clippy-check@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          toolchain: nightly
          args: --all-features
